### PR TITLE
Add Python 3.x support through Cython

### PR DESCRIPTION
**Pull request by alepulver**
It's now compatible with both Python 2 and 3. I haven't used setuptools because I didn't know how to add Cython support.

If you have time, please update the sparsesvd package in pypi. There is no alternative I'm aware of for doing SVD on sparse matrices in Python 3.x (divisi2 doesn't support 3.x, and scipy.sparse consumes a lot of memory suggesting it's converting to a dense representation). Feel free to discard changes you don't like.

### CODE REVIEW

**Comment by piskvorky** [comment]
Awesome, thanks @alepulver. I'll have a look asap.

**Comment by piskvorky** [comment]
I tried but got:

```
(test)[~]$ python --version
Python 2.7.1

(test)[~]$ uname -a
Darwin kofola2.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

(test)[~]$ ipython

In [1]: import numpy, scipy.sparse

In [2]: numpy.__version__
Out[2]: '1.7.0'

In [3]: scipy.__version__
Out[3]: '0.11.0'

In [4]: from sparsesvd import sparsesvd

In [5]: mat = numpy.random.rand(200, 100)

In [6]: smat = scipy.sparse.csc_matrix(mat)

In [7]: ut, s, vt = sparsesvd(smat, 100)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-0a159038a54e> in <module>()
----> 1 ut, s, vt = sparsesvd(smat, 100)

/Volumes/work/workspace/vew/test/lib/python2.7/site-packages/sparsesvd.so in sparsesvd.sparsesvd (sparsesvd.c:1964)()

/Volumes/work/workspace/vew/test/lib/python2.7/site-packages/sparsesvd.so in View.MemoryView.memoryview_cwrapper (sparsesvd.c:9452)()

/Volumes/work/workspace/vew/test/lib/python2.7/site-packages/sparsesvd.so in View.MemoryView.memoryview.__cinit__ (sparsesvd.c:6227)()

TypeError: 'buffer' does not have the buffer interface
```

**Comment by alepulver** [comment]
I haven't tested it before in 2.x, assuming it would either fail or work on both but I was wrong.
Sorry, it should work now.

**Comment by piskvorky** [comment]
Thanks, that did the trick!

I put back setuptools, because it has better dependency handling and tests. What was the problem with setuptools in your case?

The latest version is in the `python3` branch, can you check it still works in Python3? I'll merge after that.

**Comment by alepulver** [comment]
On 03/03/2013 09:35 AM, Radim Řehůřek wrote:

> Thanks, that did the trick!
> 
> I put back setuptools, because it has better dependency handling and
> tests. What was the problem with setuptools in your case?
> 
> None. I just didn't know how to use Cython there.
> 
> The latest version is in the |python3| branch, can you check it still
> works in Python3? I'll merge after that.
> 
> It doesn't. There are a few incompatibilities, but can be solved. I've added the change.

In short, the main issues are:
- print is not a statement anymore (needs parentheses)
- exception handling uses "as" instead of "," for binding to a variable

There was also a minor syntax error (unclosed quote in sparsesvd.pyx).

For me, it now works for both Python 2.7.3 and 3.2.

Cheers,
Alejandro

**Comment by piskvorky** [comment]
Heh, thanks for catching that, how did that even compile?

I found that using setuptools was not painless after all... there is some pyrex detection magic going on behind scenes. I added an extra patch to make it work.

I just released 0.1.9, thanks a lot Alejandro! Hopefully we didn't break things for too many people :)

**Comment by alepulver** [comment]
No problem. Thanks for updating the package.
Let me know if something breaks (it's the first time I use Cython).

**Comment by piskvorky** [comment]
I tried on another machine and got

```
$ uname -a
Linux li157-122 3.0.4-linode36 #1 SMP Thu Sep 1 20:56:39 EDT 2011 i686 GNU/Linux

$ python --version
Python 2.6.5

>>> import sparsesvd
>>> import numpy, scipy.sparse
>>> from sparsesvd import sparsesvd
>>> mat = numpy.random.rand(200, 100) # create a random matrix
>>> smat = scipy.sparse.csc_matrix(mat) # convert to sparse CSC format
>>> ut, s, vt = sparsesvd(smat, 100) # do SVD, asking for 100 factors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sparsesvd.pyx", line 30, in sparsesvd.sparsesvd (sparsesvd.c:1938)
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```

:(

scipy 0.11, numpy 1.7.0, 32bit system

**Comment by alepulver** [comment]
On 03/03/2013 01:51 PM, Radim Řehůřek wrote:

> I tried on another machine and got
> 
> |$ uname -a
> Linux li157-122 3.0.4-linode36 #1 SMP Thu Sep 1 20:56:39 EDT 2011 i686 GNU/Linux
> 
> $ python --version
> Python 2.6.5
> 
> > > > import sparsesvd
> > > > import numpy, scipy.sparse
> > > > from sparsesvd import sparsesvd
> > > > mat = numpy.random.rand(200, 100) # create a random matrix
> > > > smat = scipy.sparse.csc_matrix(mat) # convert to sparse CSC format
> > > > ut, s, vt = sparsesvd(smat, 100) # do SVD, asking for 100 factors
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > >   File "sparsesvd.pyx", line 30, in sparsesvd.sparsesvd (sparsesvd.c:1938)
> > > > ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
> > > > |
> 
> :(
> 
> scipy 0.11, numpy 1.7.0
> 
> Could you please try with Python 2.7.3? According to the documentation,
> memoryviews were backported from Python 3.1 to Python 2.7 but not 2.6.

If it works with 2.7 but not 2.6 and you really need supporting that
version, we could try with the old ndarray interface (uncommenting the
lines after "old style" and commenting the next block in sparsesvd.pyx).

Cheers,
Alejandro

**Comment by piskvorky** [comment]
I tried installing sparsesvd on another Debian machine (64bit) with python 2.6.6, and it works fine there.

Python 2.6 is the default in debian, so if that's really the problem, it's a big one. We can drop support for 2.5, but not for 2.6. But I'm thinking it's maybe more connected to the 32 vs 64 bit?

**Comment by alepulver** [comment]
I'm also thinking it's related to 32 vs 64 bit. According to these posts, maybe changing np.long to np.int64 fixes it. This is because in 32-bit "long" is 4 bytes and in 64-bit it's 8 bytes, while intNN are always NN bits (or at least should be).

http://stackoverflow.com/questions/9481295/cython-numpy-type-of-an-array
http://stackoverflow.com/questions/9452427/using-cython-with-my-numpy-program

**Comment by piskvorky** [comment]
Ok, thanks. Can you do a pull requests with a fix?

I think most people who need high performance sparse SVD run 64bit anyway, but let's keep things clean and proper anyway.

**Comment by alepulver** [comment]
I see two possible causes of the problem: either numpy.lorg != long or there may be a bug in Cython.

Could you please send me the following data from the machine that failed?
- The sparsesvd.c file generated by Cython (when using `python setup.py build`).
- The output of the following C program, just to be sure.
  
  ``` C
  #include <stdio.h>
  int main() {
  printf("long is %ld\nlong long is %ld\n", sizeof(long), sizeof(long long));
  }
  ```
- The output of the following Python script.
  
  ``` python
  import numpy as np
  print np.dtype(long)
  print np.dtype(long).itemsize
  print np.dtype(np.long)
  print np.dtype(np.long).itemsize
  ```

Depending on the result, I'll make a pull request to (hopefully) fix it.

**Comment by piskvorky** [comment]
Output of the C program:

```
long is 4
long long is 8
```

Python program:

```
int64
8
int64
8
```

The generated `sparsesvd.c` file is at http://radimrehurek.com/gensim/sparsesvd.c

Btw this is a standard linode 512 machine with Debian (the same one that powers radimrehurek.com)

**Comment by alepulver** [comment]
As expected, numpy.long is 8 bytes, which is not compatible with C's "long" (4 bytes). I've committed a two line change to replace np.long with np.dtype('l'), please fetch it from my repository. It "should" work.

About the other report, I'll look into it.

Keep in mind that in 32-bit the range of matrix dimensions is reduced. This was like this even before moving to Cython, because of C's semantics. I believe that might be the reason Python/NumPy developers chose 8 byte integers in both architectures, or maybe just for (forward) compatibility.

**Comment by piskvorky** [comment]
Ok, will fetch and test, thanks .

**Comment by piskvorky** [comment]
Cool, works now. I'll test on more machines.

I added you to the github repo collaborators, so you can push directly here. Most of the code is now yours anyway :)

**Comment by piskvorky** [comment]
By the way, not related to the upgrade but -- someone reported `sparsesvd` returning fewer dimensions than requested (492 when asked for 500 etc). Have you ever come across this behaviour of (I assume) SVDLIBC?

**Comment by alepulver** [comment]
Thanks for adding me as a collaborator.

Yes, once; it seemed strange. When asking for 142 (maximum size of matrix dimensions) it returned that number of dimensions, but when asking for 50 I got only 43. I'll check if I still have that matrix around...

**Pull request merged**
